"use client";
import Contact from "@/components/contact";
import Header from "@/components/header";
import ScrollTop from "@/components/utils/scroll-top";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";
import "./i18n";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={twMerge(inter.className, "pb-4")}>
        <ThemeProvider attribute="class">
          <Header />
          {children}
          <Contact />
          <ScrollTop />
        </ThemeProvider>
      </body>
    </html>
  );
}
